jobs/urls.py
from django.urls import path, include
from .views import *
from . import views
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    path('', HomeView.as_view(), name='jobs-home'),
    path('companies/', CompanyListView.as_view(), name='jobs-companies'),
    path('companies/<int:pk>', CompanyDetailView.as_view(), name='jobs-company-details'),
    path('companies/edit/<int:pk>', CompanyUpdateView.as_view(), name='jobs-company-update'),
    path('companies/new', CompanyCreateView.as_view(extra_context={'title': 'Add Company'}),
        name='jobs-new-company'),
    path('companies/delete/<int:pk>', CompanyDeleteView.as_view(), name='jobs-company-delete'),
    path('positions/', PositionListView.as_view(), name='jobs-list-positions'),
    path('positions/new', PositionCreateView.as_view(), name='jobs-new-position'),
    path('positions/<int:pk>', PositionDetailView.as_view(), name='jobs-position-details'),
    path('positions/edit/<int:pk>', PositionUpdateView.as_view(), name='jobs-update-position'),
    path('positions/delete/<int:pk>', PositionDeleteView.as_view(), name='jobs-delete-position'),
    path('skill/', SkillListView.as_view(), name='jobs-list-skill'),
    path('skill/new', SkillCreateView.as_view(), name='jobs-new-skill'),
    path('skill/edit/<int:pk>', SkillUpdateView.as_view(), name='jobs-update-skill'),
    path('skill/delete/<int:pk>', SkillDeleteView.as_view(), name='jobs-delete-skill'),
    path('applications/', ApplicationListView.as_view(), name='jobs-list-applications'),
    path('applications/new', ApplicationCreateView.as_view(), name='jobs-new-application'),
    path('applications/<int:pk>', ApplicationDetailView.as_view(), name='jobs-detail-application'),
    path('applications/edit/<int:pk>', ApplicationUpdateView.as_view(), name='jobs-update-application'),
    path('applications/delete/<int:pk>', ApplicationDeleteView.as_view(), name='jobs-delete-application'),
    path('applications/<int:pk>/interview/', InterviewCreateView.as_view(), name='jobs-new-interview'),
    path('applications/<int:app_pk>/interview/edit/<int:pk>', InterviewUpdateView.as_view(), name='jobs-update-interview'),
    path('applications/<int:app_pk>/interview/delete/<int:pk>', InterviewDeleteView.as_view(), name='jobs-delete-interview'),
    path('applications/<int:pk>/assessment/', AssessmentCreateView.as_view(), name='jobs-new-assessment'),
    path('applications/<int:app_pk>/assessment/edit/<int:pk>', AssessmentUpdateView.as_view(), name='jobs-update-assessment'),
    path('applications/<int:app_pk>/assessment/delete/<int:pk>', AssessmentDeleteView.as_view(), name='jobs-delete-assessment'),
    path('contacts/', ContactListView.as_view(), name='jobs-contacts'),
    path('contacts/new', ContactCreateView.as_view(), name='jobs-new-contact'),
    path('contacts/<int:pk>', ContactUpdateView.as_view(), name='jobs-update-contact'),
    path('contacts/delete/<int:pk>', ContactDeleteView.as_view(), name='jobs-delete-contact'),
    path('communications/', CommunicationListView.as_view(), name='jobs-list-communications'),
    path('communications/new', CommunicationCreateView.as_view(extra_context={'title': 'Add Communication'}), 
            name='jobs-new-communication'),
    path('communications/<int:pk>', CommunicationUpdateView.as_view(), name='jobs-update-communication'),
    path('communications/delete/<int:pk>', CommunicationDeleteView.as_view(), name='jobs-delete-communication'),
    path('parse_job_url', views.parse_job_url, name='parse-job-url'),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', user_views.register, name='register'),
    path('upload/', user_views.DocumentCreateView.as_view(), name='upload'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('accounts/', include('allauth.urls')),

]

jobtracker/urls.py
"""job_tracker URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
]

jobs/models.py
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.contrib.auth.models import User
from users.models import Document


class Skill(models.Model):

	# Columns in Skill table
	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		default=1
		)

	skill_name = models.CharField(max_length=100)

	def __str__(self):
		"""String for representing the Skill as the Skill name"""
		return self.skill_name


class Company(models.Model):
	INDUSTRY_CHOICES = [
		('tech', 'Tech'),
		('ecommerce', 'Ecommerce'),
		('gaming', 'Gaming'), 
		('healthcare', 'Healthcare'),
		('pharma', 'Pharmaceutical'),
		('aerospace', 'Aerospace'),
		('fintech', 'FinTech'),
		('nonprofit', 'Nonprofit'),
		('defense', 'Defense'),
		('other', 'Other'),
	]

	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		default=1)
	name = models.CharField(max_length=100)
	careers_url = models.URLField(max_length=1000, null=True, blank=True)
	industry = models.CharField(choices=INDUSTRY_CHOICES, max_length=100, null=True, blank=True)

	def num_company_apps(self):
		num_apps = 0
        
		for position in self.position_set.all():
			num_apps += position.num_apps()

		return num_apps

	def __str__(self):
		"""String for representing the Company as the Company name"""
		return self.name


class Position(models.Model):

	# Columns in Position table
	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		default=1
		)
	company = models.ForeignKey(
		Company,
		on_delete=models.CASCADE
		)
	position_title = models.CharField(max_length=100)
	position_url = models.URLField(max_length=1000, null=True)
	date_opened = models.DateField(null=True)
	date_closed = models.DateField(null=True, blank=True, default='')
	skills = models.ManyToManyField(Skill, blank=True)
	job_description = models.TextField(null=True)

	def num_apps(self):
		return Application.objects.filter(position=self).count()

	def __str__(self):
		"""String for representing the Position as the Position name"""
		return self.position_title + ' - ' + self.company.name

	def get_absolute_url(self):
		return reverse('jobs-list-positions')


class Contact(models.Model):
	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		default=1
		)

	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	email = models.EmailField(null=True, blank=True, max_length=128)
	phone_number = models.IntegerField(null=True, blank=True)
	notes = models.TextField(null=True, blank=True)
	
	def get_absolute_url(self):
		return reverse('jobs-contacts')

	def __str__(self):
		"""String for representing a Contact as their first and last names"""
		return self.first_name + ' ' + self.last_name


class Account(models.Model):
	user = models.OneToOneField(
		User,
        on_delete=models.CASCADE
    	)

	def __str__(self):
		return self.user.username


class Application(models.Model):
	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		default=1
		)
	position = models.ForeignKey(
		Position,
		on_delete=models.CASCADE
		)
	resume = models.ForeignKey(
		Document,
		on_delete=models.SET_NULL,
		null=True,
		blank=True)
	date_started = models.DateField(null=True, blank=True)
	date_submitted = models.DateField(null=True, blank=True)
	email_used = models.EmailField(null=True, blank=True, max_length=128)
	offer = models.BooleanField()
	accepted = models.BooleanField()
	notes = models.TextField(null=True, blank=True)

	def get_absolute_url(self):
		return reverse('jobs-list-applications')

	def __str__(self):
		company = self.position.company.name
		job_title = self.position.position_title
		return company + ' - ' + job_title


class Interview(models.Model):
	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		default=1
		)
	application = models.ForeignKey(
		Application,
		on_delete=models.CASCADE
		)
	date = models.DateField(null=True, blank=True)
	time = models.CharField(null=True, blank=True, max_length=10)
	location = models.CharField(null=True, blank=True, max_length=256)
	virtual_url = models.CharField(null=True, blank=True, max_length=512)
	complete = models.BooleanField()
	notes = models.TextField(null=True, blank=True)


class Assessment(models.Model):
	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		default=1
		)
	application = models.ForeignKey(
		Application,
		on_delete=models.CASCADE
		)
	date = models.DateField(null=True, blank=True)
	time = models.CharField(null=True, blank=True, max_length=10)
	virtual_url = models.CharField(null=True, blank=True, max_length=512)
	complete = models.BooleanField()
	notes = models.TextField(null=True, blank=True)


class Communication(models.Model):
	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		default=1
		)
	application = models.ForeignKey(
		Application,
		on_delete=models.CASCADE
		)
	contact = models.ForeignKey(
		Contact,
		on_delete=models.CASCADE
		)
	date = models.DateField(null=True, blank=True)
	method = models.CharField(choices=[('phone','Phone'), ('email','Email'), ('meeting','Meeting'),], max_length=100, null=True)
	notes = models.TextField(null=True, blank=True)

	def __str__(self):
		company = self.application.position.company.name
		job_title = self.application.position.position_title
		return self.contact.last_name + '-' + company + '-' + job_title
	
	def get_absolute_url(self):
		return reverse('jobs-list-communications')

jobs/forms.py
from django import forms
from django.forms import ModelForm, CheckboxSelectMultiple
from .models import (Position, 
                     Company,
                     Contact, 
                     Application, 
                     Communication, 
                     Interview, 
                     Assessment, 
                     Skill)
from users.models import Document


class PositionForm(ModelForm):

    class Meta: 
        model = Position
        fields = ['company', 'position_title', 'position_url', 'date_opened', 'date_closed',
                    'skills', 'job_description']
        help_texts = {
            'date_opened': 'Ex: mm/dd/yyyy or yyyy-mm-dd',
            'date_closed': 'Ex: mm/dd/yyyy or yyyy-mm-dd'
        }
        labels = {
            'position_title': 'Job Title',
            'position_url': 'Job Posting URL',
            'date_opened': 'When did the job open?',
            'date_closed': 'When did the job close? (optional)'
        }

    skills = forms.ModelMultipleChoiceField(
        queryset=Skill.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    def __init__(self, *args, **kwargs):
        ''' This filters the options in the company dropdown field to only those companies
            this user has added. Same thing for the list of Skills to chose from. 
        '''
        user = kwargs.pop('user')
        super(PositionForm, self).__init__(*args, **kwargs)
        self.fields['company'].queryset = Company.objects.filter(user=user)
        self.fields['skills'].queryset = Skill.objects.filter(user=user)


class CompanyForm(ModelForm):

    class Meta:
        model = Company
        fields = ['name', 'careers_url', 'industry']


class ApplicationForm(ModelForm):

    class Meta:
        model = Application
        exclude = ('user',)
        labels = {
            'email_used': 'What email address did you use to create this application?',
            'date_started': 'When did you start this application?',
            'date_submitted': 'If submitted, when?',
            'offer': 'Check if you\'ve received an offer',
            'accepted': 'Check if you\'ve accepted',
            'notes': 'Any notes specific to this application:'
        }

    def __init__(self, *args, **kwargs):
        ''' This filters the options in the position dropdown field to only those positions
            this user has added.
        '''
        user = kwargs.pop('user')
        super(ApplicationForm, self).__init__(*args, **kwargs)
        self.fields['position'].queryset = Position.objects.filter(user=user)
        self.fields['resume'].queryset = Document.objects.filter(user=user)


class CommunicationForm(ModelForm):

    class Meta: 
        model = Communication
        fields = ['application', 'contact', 'date', 'method', 'notes']
        help_texts = {
            'date': 'Ex: mm/dd/yyyy',
        }

    def __init__(self, *args, **kwargs):
        ''' This filters the options in the company dropdown field to only those companies
            this user has added.
        '''
        user = kwargs.pop('user')
        super(CommunicationForm, self).__init__(*args, **kwargs)
        self.fields['application'].queryset = Application.objects.filter(user=user)
        self.fields['contact'].queryset = Contact.objects.filter(user=user)


class InterviewForm(ModelForm):

    class Meta:
        model = Interview
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        ''' This filters the options in the application dropdown field to only the application
            from which the user selected to create a new interview
        '''
        pk = kwargs.pop('app_pk')
        super(InterviewForm, self).__init__(*args, **kwargs)
        self.fields['application'].queryset = Application.objects.filter(pk=pk)
        self.fields['date'].required = True


class AssessmentForm(ModelForm):

    class Meta:
        model = Assessment
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        ''' This filters the options in the application dropdown field to only the application
            from which the user selected to create a new assessment
        '''
        pk = kwargs.pop('app_pk')
        super(AssessmentForm, self).__init__(*args, **kwargs)
        self.fields['application'].queryset = Application.objects.filter(pk=pk)
        self.fields['date'].required = True


class CombinedApplicationForm(ModelForm):

    class Meta:
        model = Application
        exclude = ('user', 'company', 'position',)
        labels = {
            'email_used': 'What email address did you use to create this application?',
            'date_started': 'When did you start this application?',
            'date_submitted': 'If submitted, when?',
            'offer': 'Check if you\'ve received an offer',
            'accepted': 'Check if you\'ve accepted',
            'notes': 'Any notes specific to this application:'
        }
    
    def __init__(self, *args, **kwargs):
        ''' This filters the options in the position dropdown field to only those positions
            this user has added.
        '''
        user = kwargs.pop('user')
        super(CombinedApplicationForm, self).__init__(*args, **kwargs)
        self.fields['resume'].queryset = Document.objects.filter(user=user)


class CombinedPositionForm(ModelForm):

    class Meta:
        model = Position
        exclude = ('user', 'company', )

    skills = forms.ModelMultipleChoiceField(
        queryset=Skill.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    def __init__(self, *args, **kwargs):
        ''' This filters the options in the skills selection field to only those skills
            this user has added.
        '''
        user = kwargs.pop('user')
        super(CombinedPositionForm, self).__init__(*args, **kwargs)
        self.fields['skills'].queryset = Skill.objects.filter(user=user)


class CombinedCompanyForm(CompanyForm):

    class Meta:
        model = Company
        exclude = ('user',)
        labels = {
            'name': 'Company Name',
            'careers_url': 'Link to company careers page'
        }

jobs/templates/jobs/add_interview.html
{% extends "jobs/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container h-100 mt-5">
	<div class="container ml-3">
		<div class="row mt-3">
			<div class="col-md-auto">
				<h2>Add New Interview</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-md-auto">
				<p>Add a interview for this application</p>
				<hr>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-6 mb-3">
				<form method="POST">
				{% csrf_token %}
				{{ form|crispy }}
					<div class="row mb-3">
						<div class="col">
							<button class="btn btn-primary mt-3" type="submit">Add Interview</button>
						</div>
				    </div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

jobs/templates/jobs/companies.html
{% extends "jobs/base.html" %}

{% block content %}
<div class="container p-3 mb-3">
	<h1 class="text-center">Companies</h1>
</div>
<div class="row">
  	<div class="col-4" id="companieList">
		<a class="btn btn-primary mb-3 btn-block" href="{% url 'jobs-new-company' %}">Add New Company</a>
		<input class="form-control mb-2" id="listSearch" type="text" placeholder="Search for Company">
    	<div class="list-group" id="list-tab" role="tablist">
			{% for company in companies %}
			{% if company.id == request.GET.company|add:"0"  %}
			<a class="list-group-item list-group-item-action searchable active" id="list-{{ company.id }}-list" data-bs-toggle="list" href="#list-{{ company.id }}" role="tab" aria-controls="list-{{ company.id }}">
			{% else %}
			<a class="list-group-item list-group-item-action searchable" id="list-{{ company.id }}-list" data-bs-toggle="list" href="#list-{{ company.id }}" role="tab" aria-controls="list-{{ company.id }}">
			{% endif %}
				<div class="row">
					<div class="col-6">
						{{ company.name }}
					</div>
					<div class=col-2>
						<span class="badge bg-primary text-white rounded-pill text-center">apps {{ company.num_company_apps }}</span>
					</div>
					<div class=col-2>
						<span class="badge bg-primary text-white rounded-pill">positions {{ company.position_set.count }}</span>
					</div>
				</div>
			</a>
			{% endfor %}    
    	</div>
  	</div>
  	<div class="col-8">
    	<div class="tab-content ml-3" id="nav-tabContent">
			{% for company in companies %}
			{% if company.id == request.GET.company|add:"0"  %}
		     <div class="tab-pane fade show active" id="list-{{ company.id }}" role="tabpanel" aria-labelledby="list-{{ company.id }}-list">
		     {% else %}
		     <div class="tab-pane fade show" id="list-{{ company.id }}" role="tabpanel" aria-labelledby="list-{{ company.id }}-list">
		     {% endif %}		
		     	<div class="row">
					<div class="col mb-3">
						<h3>{{ company.name }}</h3>
						{% if company.careers_url %}
							<p class="company-url"><strong>Careers Link:</strong> {{ company.careers_url }}</p>
						{% else %}
							<p class="company-url">Update this Company to add a Careers Link</p>
						{% endif %}
						{% if company.industry %}
							<p class="company-industry"><strong>Industry:</strong> {{ company.industry }}</p>
						{% else %}
							<p class="company-industry">Update this Company to add an Industry</p>
						{% endif %}
						<div class="row mb-3">
							<div class="col">
								<a class="btn btn-primary edit-company" href="{% url 'jobs-company-update' company.id %}" role="button"><i class="bi bi-pencil-square"></i></a>
								<a class="btn btn-primary delete-company" href="{% url 'jobs-company-delete' company.id %}" role="button"><i class="bi bi-trash"></i></a>
								<a class="btn btn-primary add-position" href="{% url 'jobs-new-position' %}?company={{ company.id }}&next={{ request.path }}" role="button"><i class="bi bi-plus-lg"></i> Position</a>
							</div>
					    </div>
					</div>
				</div>
				<h3 class="mt-5">Your {{ company.name }} Job Positions:</h3>
				{% for position in company.position_set.all %}
				<div class="card mb-5 border-dark">
                    <div class="card-header position-card">
                        <div class="row">
                            <div class="col-md-8">
                                <h5>{{ position.position_title }}</h5>
                            </div>
                            <div class="col-md-4 text-right">
                                <a class="btn btn-sm btn-primary" href="{% url 'jobs-position-details' position.id %}" role="button">Position Details</a>
                            </div>
                        </div>
                    </div>
					<div class="card-body">
						<div class="row">
							<div class="col">
								{% for app in position.application_set.all %}
								<div class="mt">
									<a href="{% url 'jobs-detail-application' app.id %}" role="button"><span class="badge badge-pill bg-success text-white">You applied for this position</span></a>
								</div>
								{% empty %}
								<div class="mt">
									<a class="btn btn-sm btn-primary" href="{% url 'jobs-new-application' %}?position={{ position.id }}&next={{ request.path }}&company={{ company.id }}">Add Application</a>
								</div>								
								{% endfor %}
							</div>
						</div>
					</div>
					<div class="card-footer">
						<div class="row">
							<div class="col-8">
								<span class="card-text"><small class="text-muted"><a href="{{ position.position_url }}" class="mr-5">Link to external job posting url</a>Opened {{ position.date_opened }}</small></span>
							</div>
							<div class="col text-right">
								<a class="btn btn-sm btn-primary" href="{% url 'jobs-update-position' position.id %}?next={{ request.path }}?company={{ company.id }}" role="button"><i class="bi bi-pencil-square"></i> Position</a>
								<a class="btn btn-sm btn-primary" href="{% url 'jobs-delete-position' position.id %}?next={{ request.path }}?company={{ company.id }}" role="button"><i class="bi bi-trash"></i> Position</a>
							</div>
						</div>
					</div>
				</div>      
				{% endfor %}

		     </div>
			{% endfor %}
    	</div>
  	</div>
</div>
{% endblock content %}

jobs/templates/jobs/positions_detail.html
{% extends "jobs/base.html" %}

{% block content %}

<div class="container h-100 mt-5 mb-5">
    <div class="row mt-3">
        <div class="col-md-auto">
            <h2>Position: {{ position.position_title }}</h2>
        </div>
    </div>
    <div class="card border-primary mb-3">
        <div class="card-header position-card">
            <div class=row>
                <div class="col-md-6">
                    <h5>Position Details</h5>
                </div>
                <div class="col-md-6 text-right">
                    <a class="btn btn-sm btn-primary border-primary" href="{% url 'jobs-update-position' position.id %}?next={{ request.path }}"><i class="bi bi-pencil-square"></i> Position</a>                          
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col">
                    {% for app in position.application_set.all %}
                    <div class="mb-3">
                        <p><strong>Applications for this position: </strong><a href="{% url 'jobs-detail-application' app.id %}" role="button"><span class="badge badge-pill bg-success text-white">You applied for this position</span></a></p>
                    </div>
                    {% empty %}
                    <div class="mt-3 mb-3">
                        <p><strong>Applications for this position: </strong><a class="btn btn-sm btn-primary" href="{% url 'jobs-new-application' %}?position={{ position.id }}">Add Application</a></p>
                    </div>                              
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <p><strong>Skills:</strong></p>
                    <ul>
                        {% for skill in position.skills.all %}
                            <li>{{ skill }}</li>
                        {% endfor %}
                    </ul>
                    <p><strong>Job Description:</strong> {{ position.job_description }}</p>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <p class="card-text"><small class="text-muted"><a href="{{ position.position_url }}">Link to external job posting url</a></small></p>
            <p class="card-text"><small class="text-muted">Opened - {{ position.date_opened }}</small></p>
            <p class="card-text"><small class="text-muted">Closed - {{ position.date_closed }}</small></p>
        </div>
    </div>
</div>
{% endblock content %}

jobs/templates/jobs/skill.html
{% extends "jobs/base.html" %}

{% block content %}
<div class="container p-3 mb-3">
    <h1 class="text-center">Skills</h1>
</div>
<div class="row">
    <div class="col-4" id="skillList">
        <a class="btn btn-primary mb-3 btn-block" href="{% url 'jobs-new-skill' %}">Add New Skill</a>
        <input class="form-control mb-2" id="listSearch" type="text" placeholder="Search for Skill">
        <div class="list-group" id="list-tab" role="tablist">
            {% for skill in skills %}
            {% if skill.id == request.GET.skill|add:"0"  %}
            <a class="list-group-item list-group-item-action searchable active" id="list-{{ skill.id }}-list" data-bs-toggle="list" href="#list-{{ skill.id }}" role="tab" aria-controls="list-{{ skill.id }}">
            {% else %}
            <a class="list-group-item list-group-item-action searchable" id="list-{{ skill.id }}-list" data-bs-toggle="list" href="#list-{{ skill.id }}" role="tab" aria-controls="list-{{ skill.id }}">
            {% endif %}
                <div class="row">
                    <div class="col-6">
                        {{ skill.skill_name }}
                    </div>
                    <div class=col-2>
                        <span class="badge bg-primary text-white rounded-pill">positions {{ skill.position_set.count }}</span>
                    </div>
                </div>
            </a>
            {% endfor %}    
        </div>
    </div>
    <div class="col-8">
        <div class="tab-content ml-3" id="nav-tabContent">
            {% for skill in skills %}
            {% if skill.id == request.GET.skill|add:"0"  %}
             <div class="tab-pane fade show active" id="list-{{ skill.id }}" role="tabpanel" aria-labelledby="list-{{ skill.id }}-list"> 
             {% else %}
            <div class="tab-pane fade show" id="list-{{ skill.id }}" role="tabpanel" aria-labelledby="list-{{ skill.id }}-list">      
            {% endif %} 
                <div class="row">
                    <div class="col mb-3">
                        <h3>{{ skill.skill_name }}</h3>
                    </div>
                    <div class="col">
                        <a class="btn btn-primary edit-skill" href="{% url 'jobs-update-skill' skill.id %}" role="button"><i class="bi bi-pencil-square"></i></a>
                        <a class="btn btn-primary delete-skill" href="{% url 'jobs-delete-skill' skill.id %}" role="button"><i class="bi bi-trash"></i></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {% if num_positions %}
                        <h5>Found in {{ skill.occurences }} ({{ skill.position_set.count }} out of {{ num_positions }}) of your positions</h5>
                        {% else %}
                        <h5>Add positions to track this skill's occurences</h5>
                        {% endif %}
                    </div>
                </div>
                <h3 class="mt-5">Your {{ skill.skill_name }} Job Positions:</h3>
                {% for position in skill.position_set.all %}
                <div class="card mb-5 border-dark">
                    <div class="card-header position-card">
                        <div class="row">
                            <div class="col-md-8">
                                <h5>{{ position }}</h5>
                            </div>
                            <div class="col-md-4 text-right">
                                <a class="btn btn-sm btn-primary" href="{% url 'jobs-position-details' position.id %}" role="button">Position Details</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                {% for app in position.application_set.all %}
                                <div class="mt">
                                    <a href="{% url 'jobs-detail-application' app.id %}" role="button"><span class="badge badge-pill bg-success text-white">You applied for this position</span></a>
                                </div>
                                {% empty %}
                                <div class="mt">
                                    <a class="btn btn-sm btn-primary" href="{% url 'jobs-new-application' %}?position={{ position.id }}&next={{ request.path }}&skill={{ skill.id }}">Add Application</a>
                                </div>                              
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-8">
                                <span class="card-text"><small class="text-muted"><a href="{{ position.position_url }}" class="mr-5">Link to external job posting url</a>Opened {{ position.date_opened }}</small></span>
                            </div>
                            <div class="col text-right">
                                <a class="btn btn-sm btn-primary" href="{% url 'jobs-update-position' position.id %}?next={{ request.path }}?skill={{ skill.id }}" role="button"><i class="bi bi-pencil-square"></i> Position</a>
                                <a class="btn btn-sm btn-primary" href="{% url 'jobs-delete-position' position.id %}?next={{ request.path }}?skill={{ skill.id }}" role="button"><i class="bi bi-trash"></i> Position</a>
                            </div>
                        </div>
                    </div>
                </div>      
                {% endfor %}

             </div>
            {% endfor %}
        </div>
    </div>
</div>

    

{% endblock content %}